# Generated by Django 5.1.4 on 2025-01-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_person_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
    ]
