# Generated by Django 5.1.4 on 2025-01-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
