# Generated by Django 5.1.4 on 2025-01-21 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_person_is_student'),
        ('course', '0010_alter_transaction_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('discount_percentage', models.PositiveSmallIntegerField()),
                ('maximum_discount_amount', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discount_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.discountcode')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.person')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.transaction')),
            ],
        ),
    ]
